name: "Publish TypeDoc"
on:
  push:
    branches:
      - "main"

jobs:
  publish-documentation:
    permissions:
      id-token: "write"
      pages: "write"

    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"

    runs-on: "ubuntu-latest"
    steps:
      - id: "checkout"
        name: "Check out Git repository"
        uses: "actions/checkout@v4"

      - id: "setup-node"
        name: "Set up Node.js"
        uses: "actions/setup-node@v4"

      - id: "install-dependencies"
        name: "Install Node.js dependencies"
        run: |
          set -euo pipefail
          npm install
      - id: "build"
        name: "Build documentation"
        run: |
          set -euo pipefail
          npm run docs
      - id: "upload-documentation"
        name: "Upload Pages artifact"
        uses: "actions/upload-pages-artifact@v3"
        with:
          path: "docs/"

      - id: "deployment"
        name: "Deploy documentation to GitHub Pages"
        uses: "actions/deploy-pages@v4"